{
    "status": 201,
    "response": {
        "id": 1312940398,
        "date_created": "2023-05-15T13:48:02.074-04:00",
        "date_approved": "2023-05-15T13:48:02.225-04:00",
        "date_last_updated": "2023-05-15T13:48:02.225-04:00",
        "date_of_expiration": None,
        "money_release_date": "2023-05-15T13:48:02.225-04:00",
        "money_release_status": None,
        "operation_type": "regular_payment",
        "issuer_id": "12551",
        "payment_method_id": "visa",
        "payment_type_id": "credit_card",
        "payment_method": {"id": "visa", "type": "credit_card", "issuer_id": "12551"},
        "status": "approved",
        "status_detail": "accredited",
        "currency_id": "PEN",
        "description": None,
        "live_mode": False,
        "sponsor_id": None,
        "authorization_code": None,
        "money_release_schema": None,
        "taxes_amount": 0,
        "counter_currency": None,
        "brand_id": None,
        "shipping_amount": 0,
        "build_version": "2.142.4",
        "pos_id": None,
        "store_id": None,
        "integrator_id": None,
        "platform_id": None,
        "corporation_id": None,
        "payer": {
            "first_name": None,
            "last_name": None,
            "email": "test_user_80507629@testuser.com",
            "identification": {"number": "32659430", "type": "DNI"},
            "phone": {"area_code": None, "number": None, "extension": None},
            "type": None,
            "entity_type": None,
            "id": "1285239263",
        },
        "collector_id": 1284359916,
        "marketplace_owner": None,
        "metadata": {},
        "additional_info": {
            "available_balance": None,
            "nsu_processadora": None,
            "authentication_code": None,
        },
        "order": {},
        "external_reference": None,
        "transaction_amount": 50,
        "transaction_amount_refunded": 0,
        "coupon_amount": 0,
        "differential_pricing_id": None,
        "financing_group": None,
        "deduction_schema": None,
        "installments": 1,
        "transaction_details": {
            "payment_method_reference_id": None,
            "acquirer_reference": None,
            "net_received_amount": 46.46,
            "total_paid_amount": 50,
            "overpaid_amount": 0,
            "external_resource_url": None,
            "installment_amount": 50,
            "financial_institution": None,
            "payable_deferral_period": None,
        },
        "fee_details": [
            {"type": "mercadopago_fee", "amount": 3.54, "fee_payer": "collector"}
        ],
        "charges_details": [],
        "captured": True,
        "binary_mode": False,
        "call_for_authorize_id": None,
        "statement_descriptor": "MBVSAPSKWBANBLYJH",
        "card": {
            "id": None,
            "first_six_digits": "400917",
            "last_four_digits": "6176",
            "expiration_month": 11,
            "expiration_year": 2025,
            "date_created": "2023-05-15T13:48:02.000-04:00",
            "date_last_updated": "2023-05-15T13:48:02.000-04:00",
            "cardholder": {
                "name": "Maria Huamancusi",
                "identification": {"number": "12345678", "type": "DNI"},
            },
        },
        "notification_url": None,
        "refunds": [],
        "processing_mode": "aggregator",
        "merchant_account_id": None,
        "merchant_number": None,
        "point_of_interaction": {
            "type": "UNSPECIFIED",
            "business_info": {"unit": "online_payments", "sub_unit": "sdk"},
        },
        "accounts_info": None,
        "tags": None,
    },
}
