# Generated by Django 4.2.1 on 2023-05-14 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='Course',
        ),
    ]
